const numero = Number(prompt("Digite um numero inteiro para obter a tabuada do 0 ao 10." ))
const resultado0 = ( numero*0)
const resultado1=  (numero*1)
const resultado2 = ( numero*2)
const resultado3 = ( numero*3)
const resultado4 = ( numero*4)
const resultado5 = ( numero*5)
const resultado6 = ( numero*6)
const resultado7 = ( numero*7)
const resultado8 = ( numero*8)
const resultado9 = ( numero*9)
const resultado10 = ( numero*10)

alert ("multiplicado por 0 sera : " + resultado0)
alert ("multiplicado por 1 sera : " + resultado1)
alert ("multiplicado por 2 sera :" +resultado2)
alert ("multiplicado por 6 sera : " +resultado6)
alert ("multiplicado por 7 sera :" +resultado7)
alert ("multiplicado por 8 sera : " +resultado8)
alert ("multiplicado por 9 sera :" +resultado9)
alert ("multiplicado por 10 sera" +resultado10)
 
